name: DynamicallyMotd
version: '1.1'
main: net.sleepyspeller.dynamicallymotd.DynamicallyMotd
api-version: '1.21'
commands:
  dynamicallymotd:
    description: Main command with interacting with the plugin through the game.
    usage: /<command>

permissions:
  dynamicallymotd.admin:
    description: Permission for using /dynamicallymotd
    default: false